### ISSUE TITLE
Trained CNN link doesnt exist anymore!

### ISSUE THREAD

**Issue by Bparmaksiz** [olalium/face-reconstruction#1]
Hi,
Is it possible to re upload and share the trained cnn link? the current one does not work unfortunately.
BR

**Comment by olalium** [comment]
I have now added the files required to a folder as specified in the README.

https://drive.google.com/drive/folders/13Y8zCnvccDq7bwSuwGoQWawFxlD-tCMX?usp=sharing

**Comment by Vaishu1003** [comment]
> Hi, Is it possible to re upload and share the trained cnn link? the current one does not work unfortunately. BR

hello there, were you able to run it succesfully? i'm a student and i'm facing troubles with running it. is it possible for you to help me?

**Comment by Vaishu1003** [comment]
Hello, i'm a university student and i'm facing some troubles with the execution, would you be able to help me?
